# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test
version: 2
jobs:
  build:
    working_directory: /home/circleci
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ../.
          paths:
            - node_modules
      # - store_test_results:
      #     paths: ~/react-portfolio/junit.xml