version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test

steps:
    - checkout
    - run:
        name: Install and Build React
        command: |
          npm install
          npm build
