version: 2
jobs:
  build:
    working_directory: ../.
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm
      - run: npm run test
      - persist_to_workspace:
          root: ../.
          paths:
            - node_modules
      - store_test_results:
          paths: ../junit.xml




# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test
