version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
    example-workflow:
      jobs:
        - node/test
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install
