name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: docker build . --file Dockerfile --tag trytypescript:latest
#       run: docker build . --file Dockerfile --tag testrepo/testimage:latest

#     - name: SonarCloud Scan
#       # You may pin to the exact commit or the version.
#       # uses: SonarSource/sonarcloud-github-action@f4c6e4d91ea9785ec823eaeed459042606123402
#       uses: SonarSource/sonarcloud-github-action@v1.4
#       env:
#         GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       with:
#         # Additional arguments to the sonarcloud scanner
#         # Set the sonar.projectBaseDir analysis property
#         projectBaseDir: .
              
    - uses: anchore/scan-action@v1
      with:
        image-reference: "trytypescript:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: true
        debug: true
        acs-report-enable: true
      

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AnchoreReports
        path: ./anchore-reports/

